### ISSUE TITLE
handwritten submit null file

### ISSUE THREAD

**Issue by asef18766** [Normal-OJ/Back-End#122]
# client behavior
submit a file named "something.pdf" with nothing inside
# server response
internal server error
# expected behavior
raise an exception to frontend , and display to user

**Comment by skps2010** [comment]
what error?

**Comment by Bogay** [comment]
need test case for this behaviour

**Comment by asef18766** [comment]
```sh
# testcase example
touch something.pdf
```
but now in s2 it will be 200 , which i think is not allowed
