### ISSUE TITLE
Member batch signup 名稱顯示有問題

### ISSUE THREAD

**Issue by ra890927** [Normal-OJ/Back-End#192]
使用 batch signup 的時候，部分 displayedName 無法正常顯示

![image](https://user-images.githubusercontent.com/48157503/222135600-205d2d16-8346-47ad-9f13-7a8a6926ca3b.png)

**Comment by uier** [comment]
batch signup 若包含有註冊過的學生（username OR email 有一個已在系統內），則系統會將學生加入課程但不會更改其他資訊，因此造成 displayedName, password, role 不如預期

未來使用者可以透過強制更新的功能去覆蓋有註冊過學生的資料，另外也已改善前端介面的說明文字，詳情請見：
#195
https://github.com/Normal-OJ/new-front-end/pull/74
