### ISSUE TITLE
Probably performance issue in course api

### ISSUE THREAD

**Issue by Bogay** [Normal-OJ/Back-End#31]
i notice that when we want to get the user's course list
backend will search for our whole db to find them

https://github.com/Normal-OJ/Back-End/blob/239046159a87c45b9b916af994243d35a7a6b7e1/model/course.py#L43-L50

i think that will lead to poor performance, and we have a cache field in User (`User.courses`)

**Comment by skps2010** [comment]
invalid? what does that mean?

**Comment by Bogay** [comment]
it means "This doesn't seem right"

**Comment by skps2010** [comment]
已解決
