### ISSUE TITLE
Performance implication of ranking feature

### ISSUE THREAD

**Issue by AlaRduTP** [Normal-OJ/Back-End#32]
Maybe every time we request the ranking api, we should not get all of the submissions in the database.
https://github.com/Normal-OJ/Back-End/blob/239046159a87c45b9b916af994243d35a7a6b7e1/model/ranking.py#L17-L24
 We can cache `ACProblem`, `ACSubmission`, and `Submission` in the User field.

**Comment by skps2010** [comment]
ok

**Comment by skps2010** [comment]
done
