### ISSUE TITLE
Incorrect target_thread DEPTH definition

### ISSUE THREAD

**Issue by Uier** [Normal-OJ/Back-End#34]
A Post has two layers of comment, namely, users can reply a comment(but cannot reply a comment which is a reply of a comment)
the code should be:
```python
if new_depth > 2 :
    # correct condition
```
https://github.com/Normal-OJ/Back-End/blob/e7c66a9e0f84bba36963d273d9778fdeed18aacd/mongo/post.py#L56-L63

**Comment by skps2010** [comment]
sloved
