### ISSUE TITLE
Lack of email MD5 in JWT

### ISSUE THREAD

**Issue by Uier** [Normal-OJ/Back-End#44]
Why there is no MD5 found in JWT?
As title, this requirement is in need. Please <(_ _)>

**Comment by AlaRduTP** [comment]
https://ntnuoj.slack.com/archives/CLEQSAR5W/p1575868281000800

As we have talked about, the MD5 of a logged in user can be retrieved from the email.
User's email has already existed in the token.

**Comment by AlaRduTP** [comment]
Okay, I added it anyway.

Close.

**Comment by Uier** [comment]
Sorry, Front-End team leader is a trouble maker obviously
