### ISSUE TITLE
Did NOT check problemId

### ISSUE THREAD

**Issue by Uier** [Normal-OJ/Back-End#47]
https://github.com/Normal-OJ/Back-End/blob/6e49a73ac6b75a2c3c53cce12112797d7378fb5b/mongo/homework.py#L59-L64
Since `problemId` may not exist, which will make server crashed.
Should improve as:
```python3
if problem is not None:
    problem.homeworks.append(homework) 
    problem.save() 
```

**Comment by skps2010** [comment]
我處理好矣
