### ISSUE TITLE
New Requirement about Problem content

### ISSUE THREAD

**Issue by Uier** [Normal-OJ/Back-End#58]
origin: `desc`
require: `desc`, `input`, `output`, `sample_input`, `sample_output`
Note that `sample_input`, `sample_output` should be Array. 
Since a Problem may have multiple example

**Comment by Uier** [comment]
`desc` means description
`input` means input description
`output` means output description

**Comment by Uier** [comment]
new require: `hint`
which is a string

**Comment by skps2010** [comment]
done
