### ISSUE TITLE
exception handling when create error problem

### ISSUE THREAD

**Issue by asef18766** [Normal-OJ/Back-End#82]
### action
send /api/problem/manage a wrong formatted data
### expected behavior
raise an exception and skip this request
### current behavior
raise an exception but created an problem

**Comment by Bogay** [comment]
which branch the bug occurred?

**Comment by Bogay** [comment]
And can you provide a example of wrong problem data for testing?

**Comment by asef18766** [comment]
> which branch the bug occurred?
i use noj-helper on branch 4347e709037a9f35889bc6f66a571fde94ad0f50 , but now the bug can not be represented on the newest Back-End master
