### ISSUE TITLE
Use gridfs to save submission `stdout`/`stderr` 

### ISSUE THREAD

**Issue by Bogay** [Normal-OJ/Back-End#88]
Big test data will cause big output, which will cause querying slowly.
use `mongoengine`'s `FileField` to get better performance.
also, need a new route to send the test data zip file to frontend.

**Comment by as535364** [comment]
pymongo.errors.OperationFailure: Executor error during find command :: caused by :: Sort operation used more than the maximum 33554432 bytes of RAM. Add an index, or specify a smaller limit.
